#!/usr/bin/env python3
"""Does the installed scaffld actually work?

Run against a freshly installed wheel or sdist, never the repository.

scaffld's public Python API is deliberately tiny — the product is the CLI — so
this checks what a user actually does: that the templates are discoverable and
that generating a project produces the files it promises. Offline: no venv is
created and nothing is installed.
"""
from __future__ import annotations

import importlib.metadata
import subprocess
import sys
import tempfile
from pathlib import Path

DISTRIBUTION = "scaffld"


def main() -> int:
    import scaffld
    from scaffld.templates import discover

    installed = importlib.metadata.version(DISTRIBUTION)
    if scaffld.__version__ != installed:
        print(f"FAIL  __version__ is {scaffld.__version__} but metadata says {installed}")
        return 1
    print(f"ok    {DISTRIBUTION} {installed}")

    # A scaffolder that ships no templates installs fine and does nothing.
    templates = sorted(discover().keys())
    for expected in ("python-lib", "python-cli", "python-api"):
        if expected not in templates:
            print(f"FAIL  template {expected!r} missing from {templates}")
            return 1
    print(f"ok    {len(templates)} templates bundled: {', '.join(templates)}")

    # The thing it exists to do.
    with tempfile.TemporaryDirectory() as tmp:
        result = subprocess.run(
            [sys.executable, "-m", "scaffld", "new", "Smoke Project",
             "-t", "python-lib", "-a", "Fernando Aporta Franco",
             "-d", "Generated by the release smoke test.",
             "--no-input", "--no-venv", "-o", tmp],
            capture_output=True, text=True, timeout=120,
        )
        if result.returncode != 0:
            print(f"FAIL  generation exited {result.returncode}\n{result.stderr[:400]}")
            return 1

        project = Path(tmp) / "smoke-project"
        required = ["pyproject.toml", "README.md", "LICENSE", "src", "tests"]
        absent = [f for f in required if not (project / f).exists()]
        if absent:
            print(f"FAIL  the generated project is missing {absent}")
            return 1
        print(f"ok    generated a python-lib project with {', '.join(required)}")

        # The generated pyproject must carry the author it was given, not a
        # placeholder: that substitution is the whole mechanism.
        pyproject = (project / "pyproject.toml").read_text(encoding="utf-8")
        if "Fernando Aporta Franco" not in pyproject:
            print("FAIL  the generated pyproject.toml did not receive the author")
            return 1
        print("ok    template variables were substituted, not left as placeholders")

    print("\nsmoke test passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
